export const REPORT_PAYMENTS_PDF_LABELS = {
    reportCode: "RAPPORT",
    emitter: "ÉMETTEUR",
    periodSection: "PÉRIODE & RESTITUTION",
    company: "Société",
    nif: "NIF",
    isf: "ISF",
    generatedAt: "Généré le",
    dateFrom: "Date Début",
    dateTo: "Date Fin",
    tableTitle: "PAIEMENTS DE FACTURES",
    columns: {
        reference: "Référence",
        clientName: "Nom client",
        amount: "Montant",
        date: "Date",
    },
    empty: "Aucun paiement trouvé pour les critères sélectionnés.",
    page: "Page 1 sur 1",
} as const;
