export const REPORT_INVOICE_EDITION_PDF_LABELS = {
    reportCode: "RAPPORT",
    emitter: "ÉMETTEUR",
    periodSection: "PÉRIODE & RESTITUTION",
    company: "Société",
    nif: "NIF",
    isf: "ISF",
    generatedAt: "Généré le",
    dateFrom: "Date Début",
    dateTo: "Date Fin",
    tableTitle: "ÉDITION DES FACTURES",
    columns: {
        clientName: "Nom client",
        invoiceAmount: "Montant facture",
        taxAmount: "Montant taxe",
        paidAmount: "Montant payé",
        totalAmount: "Montant total",
        currency: "Devise",
        invoiceType: "Type facture",
        dueDate: "Date échéance",
    },
    empty: "Aucune facture trouvée pour les critères sélectionnés.",
    page: "Page 1 sur 1",
} as const;
