export const REPORT_A_PDF_LABELS = {
    reportCode: "RAPPORT",
    emitter: "ÉMETTEUR",
    periodSection: "PÉRIODE & RESTITUTION",
    company: "Société",
    nif: "NIF",
    isf: "ISF",
    generatedAt: "Généré le",
    dateFrom: "Date Début",
    dateTo: "Date Fin",
    tableTitle: "INVENTAIRE & FLUX DES ARTICLES (PÉRIODIQUE)",
    columns: {
        code: "CODE",
        designation: "DÉSIGNATION",
        unitPrice: "PRIX UNITAIRE",
        tax: "TVA",
        qtySold: "QUANTITÉ VENDUE",
        qtyReturned: "QUANTITÉ RETOURNÉE",
        fiscalStock: "QUANTITÉ EN STOCK",
    },
    total: "TOTAL",
    page: "Page 1 sur 1",
} as const;
